---
language: node_js
node_js:
  - "8"
services:
  - mongodb
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - DEBUG=bouncer,bouncer:* OAUTH_CLIENT_ID=none OAUTH_CLIENT_SECRET=none OAUTH_STARTUP_TEST=false npm start &
  - sleep 5
  - DEBUG=* npm test
